import React, { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  ChevronDown, ArrowLeft, HelpCircle
} from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import Header from '../Header';
import Footer from '../Footer';

const FAQ_DATA = [
  {
    id: 'what-is-nirikshak',
    category: 'general',
    question: 'What is NIRIKSHAK AI?',
    questionHi: 'निरीक्षक एआई (NIRIKSHAK AI) क्या है?',
    answer: 'NIRIKSHAK AI is an AI-powered national risk intelligence and forensic monitoring platform specifically engineered for the Member of Parliament Local Area Development Scheme (MPLADS). It continuously monitors, flags discrepancies, tracks contractor cartels, and evaluates public project execution integrity across all 543 Lok Sabha and 245+ Rajya Sabha tenures.',
    answerHi: 'निरीक्षक एआई एक कृत्रिम बुद्धिमत्ता-संचालित राष्ट्रीय जोखिम आसूचना और फोरेंसिक निगरानी मंच है, जिसे संसद सदस्य स्थानीय क्षेत्र विकास योजना (MPLADS) के लिए तैयार किया गया है। यह देश भर में स्वीकृत विकास परियोजनाओं, ठेकेदारों और फंड उपयोग की वास्तविक समय में निगरानी और विश्लेषण करता है।'
  },
  {
    id: 'what-is-mplads',
    category: 'general',
    question: 'What is MPLADS?',
    questionHi: 'एमपीलैड्स (MPLADS) योजना क्या है?',
    answer: 'MPLADS stands for Member of Parliament Local Area Development Scheme. It is a central government scheme launched in December 1993, administered by the Ministry of Statistics and Programme Implementation (MoSPI). Under this scheme, each Member of Parliament can recommend developmental works of durable nature (such as drinking water, education, public health, sanitation, roads, and community facilities) with an annual entitlement of ₹5 Crore per parliamentary constituency.',
    answerHi: 'एमपीलैड्स (सांसद स्थानीय क्षेत्र विकास योजना) भारत सरकार के सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI) द्वारा संचालित एक केंद्रीय योजना है। इसके तहत प्रत्येक संसद सदस्य को अपने क्षेत्र में टिकाऊ सामुदायिक संपत्तियों (सड़क, पेयजल, स्कूल, अस्पताल आदि) के निर्माण के लिए प्रति वर्ष ₹5 करोड़ तक के कार्यों की सिफारिश करने का अधिकार होता है।'
  },
  {
    id: 'problems-detected',
    category: 'detection',
    question: 'What problems does NIRIKSHAK AI detect?',
    questionHi: 'निरीक्षक एआई किन समस्याओं और विसंगतियों की पहचान करता है?',
    answer: 'NIRIKSHAK AI monitors 8 distinct anomaly dimensions including:\n• Fiscal burn anomalies: Rapid fund releases right before fiscal year-ends without matching work progress.\n• Physical vs. financial gaps: Projects where 80%+ funds have been disbursed but physical site progress is stalled below 30%.\n• Contractor cartels: Recurrent non-competitive contract awards to clustered agencies sharing common addresses, phones, or bank branches.\n• Duplicate works: Re-sanctioning the same civil asset (e.g. road stretch or borewell) across changing parliamentary terms.\n• Chronic timeline stagnation: Works approved years ago with zero execution progress or missing Completion Certificates.\n• Tender limit splitting: Breaking single large works into multiple small sub-sanctions to evade mandatory formal tender thresholds.',
    answerHi: 'निरीक्षक एआई 8 प्रमुख विसंगतियों का पता लगाता है:\n• वित्तीय व्यय विसंगतियां: बिना कार्य प्रगति के अंतिम समय में फंड डंपिंग।\n• भौतिक बनाम वित्तीय अंतर: 80% से अधिक फंड जारी लेकिन जमीनी काम 30% से कम।\n• ठेकेदार कार्टेल: एक ही पते या बैंक खाते से जुड़े वेंडरों को बार-बार ठेके मिलना।\n• दोहराव कार्य: एक ही स्थान पर समान कार्य की दोबारा स्वीकृति।\n• असामान्य देरी: सालों पहले स्वीकृत कार्य जो बिना किसी प्रगति के अटके हुए हैं।\n• टेंडर विभाजन: टेंडर नियमों से बचने के लिए बड़े कार्यों को छोटे टुकड़ों में बांटना।'
  },
  {
    id: 'how-risk-calculated',
    category: 'methodology',
    question: 'How is the risk score calculated?',
    questionHi: 'परियोजना का जोखिम स्कोर (Risk Score) कैसे निर्धारित होता है?',
    answer: 'Every project receives a composite Risk Score from 0 to 100. This score is generated by weighting the 8 independent forensic risk pillars against established ministry baselines, district schedules of rates, and historical performance distributions. Scores are categorized into three operational risk bands:\n• Low Risk (0–39): Normal progress conforming to scheme parameters.\n• Average Risk (40–69): Minor delays, cost deviations, or pending utilization documents requiring review.\n• High/Critical Risk (70–100): Severe milestone discrepancies, contractor clustering, or unverified fund disbursements requiring prioritized on-site inspection.',
    answerHi: 'प्रत्येक कार्य का जोखिम स्कोर 0 से 100 के पैमाने पर 8 फोरेंसिक स्तंभों के आधार पर भारित (weighted) गणना से तय होता है। इसे तीन स्तरों में बांटा जाता है:\n• निम्न जोखिम (0–39): सामान्य प्रगति।\n• औसत जोखिम (40–69): हल्की देरी या लंबित प्रमाणपत्र।\n• उच्च/गंभीर जोखिम (70–100): गंभीर विसंगति या संदिग्ध आवंटन, जहां तत्काल भौतिक सत्यापन आवश्यक है।'
  },
  {
    id: 'eight-risk-pillars',
    category: 'methodology',
    question: 'What are the 8 risk pillars?',
    questionHi: 'निरीक्षक एआई के 8 जोखिम स्तंभ (8 Risk Pillars) कौन से हैं?',
    answer: 'The 8 forensic risk engines are:\n1. Financial Burn Anomaly (disbursement velocity vs expenditure schedule)\n2. Physical vs. Financial Gap (percentage spent vs verified percentage completed)\n3. Contractor & Cartel Clustering (vendor concentration and shared network signals)\n4. Geospatial & Asset Duplication (coordinate and description duplicate detection)\n5. Timeline & Milestone Stagnation (inactivity beyond sanctioned SLA)\n6. Sanction Deviations & Splitting (sanction ceiling bypass patterns)\n7. Verification & Evidence Compliance (Measurement Book and photo geo-tag presence)\n8. Historical Agency Reliability (implementing agency historical default and delay rate)',
    answerHi: '8 फोरेंसिक स्तंभ निम्नलिखित हैं:\n1. वित्तीय व्यय विसंगति (Financial Burn Anomaly)\n2. भौतिक बनाम वित्तीय अंतर (Physical vs Financial Gap)\n3. ठेकेदार व कार्टेल क्लस्टरिंग (Contractor & Cartel Clustering)\n4. भू-स्थानिक कार्य दोहराव (Geospatial & Asset Duplication)\n5. समय-सीमा व रुकावट विश्लेषण (Timeline & Stagnation)\n6. स्वीकृति विचलन व विभाजन (Sanction Splitting)\n7. साक्ष्य व प्रमाणपत्र अनुपालन (Evidence & UC Compliance)\n8. कार्यान्वयन एजेंसी साख (Historical Agency Reliability)'
  },
  {
    id: 'ai-final-decisions',
    category: 'governance',
    question: 'Does AI make final decisions?',
    questionHi: 'क्या कृत्रिम बुद्धिमत्ता (AI) स्वतः अंतिम निर्णय लेती है?',
    answer: 'No. NIRIKSHAK AI functions strictly as an intelligent decision-support copilot, never as an autonomous judge. An elevated risk score or anomaly flag indicates statistical discrepancies that warrant human scrutiny; it is never proof of misconduct. All final administrative determinations, inquiry launches, contractor suspensions, and site verifications are reserved exclusively for authorized District Magistrates, Nodal Officers, and Ministry Auditors.',
    answerHi: 'नहीं। निरीक्षक एआई पूरी तरह निर्णय-सहायता प्रणाली (decision-support tool) के रूप में कार्य करता है, न कि अंतिम न्यायाधीश के रूप में। कोई भी उच्च जोखिम स्कोर केवल प्रशासनिक ध्यान केंद्रित करने का संकेत है। अंतिम कानूनी, वित्तीय और निरीक्षण संबंधी निर्णय केवल अधिकृत सरकारी अधिकारियों द्वारा ही लिए जाते हैं।'
  },
  {
    id: 'data-sources',
    category: 'methodology',
    question: 'Where does the data come from?',
    questionHi: 'निरीक्षक एआई में डेटा कहां से प्राप्त होता है?',
    answer: 'NIRIKSHAK AI ingests data directly from the official Ministry of Statistics and Programme Implementation (MoSPI) public dashboards (e.g. mplads.mospi.gov.in), open government datasets, state gazettes, and verified geospatial boundary repositories. The data includes sanctioned allocations, expenditure vouchers, vendor transaction IDs, physical completion dates, and nodal implementing agency profiles.',
    answerHi: 'डेटा सीधे सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI) के आधिकारिक एमपीलैड्स डैशबोर्ड (mplads.mospi.gov.in), भारत सरकार के ओपन डेटा पोर्टल्स, राज्य गजटों और आधिकारिक भू-स्थानिक मानचित्रों से प्राप्त किया जाता है।'
  },
  {
    id: 'what-is-unified-analysis',
    category: 'features',
    question: 'What is Unified Analysis?',
    questionHi: 'यूनिफाइड एनालिसिस (Unified Analysis) क्या है?',
    answer: 'Unified Analysis is the comprehensive analytical view in NIRIKSHAK AI that integrates financial ledgers, physical progress reports, contractor relationship graphs, and geospatial coordinates into a single multi-dimensional evaluation pipeline. Instead of viewing fund releases and civil works in isolated silos, Unified Analysis correlates them to detect hidden structural patterns.',
    answerHi: 'यूनिफाइड एनालिसिस एक एकीकृत विश्लेषणात्मक दृश्य है, जो वित्तीय खर्च, जमीनी प्रगति, वेंडर नेटवर्क और भू-स्थानिक निर्देशांकों को एक साथ जोड़कर समग्र मूल्यांकन प्रस्तुत करता है।'
  },
  {
    id: 'what-is-evidence-review',
    category: 'features',
    question: 'What is Evidence Review?',
    questionHi: 'एविडेंस रिव्यू (Evidence Review) क्या है?',
    answer: 'Evidence Review is the official verification interface where District Authorities and Auditors inspect supporting project documentation. This includes geo-tagged on-site photographs, Measurement Book (MB) entries, contractor invoices, Quality Inspection reports, and statutory Utilization Certificates (UCs) submitted by executing agencies.',
    answerHi: 'एविडेंस रिव्यू एक आधिकारिक मॉड्यूल है जिसके माध्यम से जिला अधिकारी और ऑडिटर किसी परियोजना के सहायक दस्तावेजों (जियोटैग फोटो, माप पुस्तिका प्रविष्टियां, वेंडर बिल और उपयोगिता प्रमाणपत्र) की डिजिटल जांच करते हैं।'
  },
  {
    id: 'what-is-field-verification',
    category: 'features',
    question: 'What is Field Verification?',
    questionHi: 'फील्ड वेरिफिकेशन (Field Verification) क्या है?',
    answer: 'Field Verification is the operational bridge between algorithmic risk indicators and ground reality. When high-risk anomalies are identified, nodal officers dispatch junior engineers or independent field inspectors. Inspectors utilize standard mobile-compatible checklists to record ground physical completion, capture GPS-stamped site photos, verify structural quality, and upload findings back into NIRIKSHAK AI.',
    answerHi: 'फील्ड वेरिफिकेशन जमीनी निरीक्षण प्रक्रिया है। जब किसी कार्य में उच्च जोखिम पाया जाता है, तो नोडल अधिकारी फील्ड इंजीनियरों को भौतिक सत्यापन के लिए भेजते हैं जो जीपीएस फोटो और निरीक्षण चेकलिस्ट के साथ वास्तविक स्थिति दर्ज करते हैं।'
  },
  {
    id: 'who-can-access',
    category: 'governance',
    question: 'Who can access official features?',
    questionHi: 'आधिकारिक और संवेदनशील सुविधाओं का उपयोग कौन कर सकता है?',
    answer: 'While public transparency features (MP performance metrics, state rankings, and general project search) are openly accessible to every citizen, official administrative workflows require Role-Based Access Control (RBAC) authentication. Role levels include:\n• Public Citizen: Open viewing of aggregate scorecards, project directories, and MP performance.\n• District Authority (DM/DC/Nodal Officer): Evidence review, inspection task dispatch, and notice issuance within their jurisdiction.\n• Ministry Auditor (MoSPI): Nationwide cross-state forensic oversight, cartel tracing, and policy auditing.',
    answerHi: 'सार्वजनिक नागरिक बिना लॉगिन के सांसद प्रदर्शन, राज्य रैंकिंग और सामान्य परियोजना विवरण देख सकते हैं। हालांकि, फील्ड असाइनमेंट, साक्ष्य समीक्षा और नोटिस जारी करने जैसी प्रशासनिक सुविधाओं के लिए भूमिका-आधारित लॉगिन (RBAC) आवश्यक है।'
  },
  {
    id: 'replacement-for-officers',
    category: 'governance',
    question: 'Is NIRIKSHAK AI a replacement for government officers?',
    questionHi: 'क्या निरीक्षक एआई सरकारी अधिकारियों का विकल्प है?',
    answer: 'Absolutely not. NIRIKSHAK AI is designed to empower, not replace, public servants. By automating the laborious task of cross-referencing thousands of rows of ledger data, it acts as a force multiplier for honest officers—highlighting the 5% of projects that require urgent attention, while freeing up administrative time to deliver community welfare faster and with higher fidelity.',
    answerHi: 'बिल्कुल नहीं। निरीक्षक एआई सरकारी अधिकारियों का विकल्प नहीं बल्कि उनका सहायक है। यह हजारों फाइलों के भारी काम को स्वचालित करके अधिकारियों का समय बचाता है ताकि वे वास्तविक समस्याओं पर ध्यान केंद्रित कर सकें और विकास कार्यों को गति दे सकें।'
  }
];

const FaqView = () => {
  const navigate = useNavigate();
  const { language } = useLanguage();
  const isHi = language === 'hi';

  const [selectedCategory, setSelectedCategory] = useState('all'); // 'all' | 'general' | 'methodology' | 'detection' | 'governance' | 'features'
  const [openIndex, setOpenIndex] = useState(0); // Accordion: only one open at a time (first one default)

  const categories = [
    { id: 'all', label: isHi ? 'सभी प्रश्न' : 'All Questions' },
    { id: 'general', label: isHi ? 'सामान्य परिचय' : 'General & Overview' },
    { id: 'methodology', label: isHi ? 'जोखिम प्रणाली' : 'Risk Methodology' },
    { id: 'detection', label: isHi ? 'विसंगति पहचान' : 'Anomaly Detection' },
    { id: 'features', label: isHi ? 'प्लेटफॉर्म फीचर्स' : 'Platform Features' },
    { id: 'governance', label: isHi ? 'शासन एवं सुरक्षा' : 'Governance & RBAC' }
  ];

  // Filtered FAQ items by category
  const filteredFaqs = useMemo(() => {
    return FAQ_DATA.filter((item) => {
      return selectedCategory === 'all' || item.category === selectedCategory;
    });
  }, [selectedCategory]);

  const toggleAccordion = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div style={{ background: 'var(--color-bg-light)', color: 'var(--color-text-primary)', minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* ─── 1. NAVBAR ─── */}
      <Header
        activeSection={null}
        setActiveSection={() => {}}
        onFeatureSelect={(id) => navigate(`/features/${id}`)}
      />

      {/* ─── 2. MAIN CONTENT ─── */}
      <main style={{ flex: 1, paddingTop: '105px', paddingBottom: '4rem' }}>
        <div style={{ maxWidth: '980px', margin: '0 auto', padding: '0 1.5rem' }}>

          {/* Breadcrumbs & Back Navigation */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', flexWrap: 'wrap', gap: '1rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.85rem', color: 'var(--color-text-secondary)' }}>
              <span
                onClick={() => navigate('/')}
                style={{ cursor: 'pointer', color: '#1D1E22', fontWeight: 600 }}
              >
                {isHi ? 'होम' : 'Home'}
              </span>
              <span>/</span>
              <span style={{ color: '#0A2458', fontWeight: 700 }}>
                {isHi ? 'अक्सर पूछे जाने वाले प्रश्न' : 'FAQ'}
              </span>
            </div>

            <button
              type="button"
              onClick={() => navigate('/')}
              className="btn-outline-dark"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.45rem',
                padding: '0.45rem 0.95rem',
                fontSize: '0.82rem',
                fontWeight: 700,
                background: '#FFFFFF',
                border: '1.5px solid #1D1E22',
                borderRadius: 'var(--radius-sm)',
                boxShadow: '2px 2px 0px #1D1E22',
                cursor: 'pointer'
              }}
            >
              <ArrowLeft size={15} strokeWidth={2.4} />
              <span>{isHi ? 'मुख्य पृष्ठ पर वापस जाएं' : 'Back to Home'}</span>
            </button>
          </div>

          {/* ─── HERO HEADER ─── */}
          <div
            style={{
              background: '#FFFFFF',
              border: '1.5px solid #1D1E22',
              borderRadius: 'var(--radius-lg)',
              boxShadow: '3px 4px 0px #1D1E22',
              padding: 'clamp(2rem, 3.5vw, 3rem)',
              marginBottom: '2rem',
              textAlign: 'left'
            }}
          >
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.45rem', background: '#E8F5E9', border: '1px solid #1E7E34', borderRadius: 'var(--radius-full)', padding: '0.3rem 0.85rem', marginBottom: '1rem' }}>
              <HelpCircle size={15} color="#1E7E34" />
              <span style={{ fontSize: '0.72rem', fontWeight: 800, color: '#1E7E34', letterSpacing: '0.08em', textTransform: 'uppercase' }}>
                {isHi ? 'ज्ञान केंद्र एवं मार्गदर्शन' : 'Knowledge Base & Methodology'}
              </span>
            </div>

            <h1
              style={{
                fontFamily: 'var(--font-serif-primary)',
                fontSize: 'clamp(2.2rem, 4vw, 3rem)',
                fontWeight: 800,
                color: '#1D1E22',
                margin: '0 0 0.85rem 0',
                lineHeight: 1.2
              }}
            >
              {isHi ? 'अक्सर पूछे जाने वाले प्रश्न' : 'Frequently Asked Questions'}
            </h1>

            <p
              style={{
                fontSize: '1.05rem',
                lineHeight: 1.6,
                color: 'var(--color-text-secondary)',
                margin: 0,
                maxWidth: '750px'
              }}
            >
              {isHi
                ? 'निरीक्षक एआई कैसे कार्य करता है, जोखिम स्कोरिंग के पीछे क्या गणितीय तर्क है, और यह प्रणाली प्रशासनिक निगरानी को कैसे सशक्त बनाती है—सभी महत्वपूर्ण प्रश्नों के उत्तर यहां प्राप्त करें।'
                : 'Explore detailed explanations on how NIRIKSHAK AI evaluates MPLADS civil works, calculates explainable risk scores, and empowers transparent public-service governance.'}
            </p>
          </div>

          {/* ─── CATEGORY FILTER ─── */}
          <div
            style={{
              background: '#FAF8F3',
              border: '1.5px solid #1D1E22',
              borderRadius: 'var(--radius-md)',
              padding: '1rem 1.25rem',
              boxShadow: '3px 4px 0px #1D1E22',
              marginBottom: '2rem',
              display: 'flex',
              gap: '0.5rem',
              flexWrap: 'wrap'
            }}
          >
            {/* Category Filter Pills */}
            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', width: '100%' }}>
              {categories.map((cat) => {
                const isSelected = selectedCategory === cat.id;
                return (
                  <button
                    key={cat.id}
                    type="button"
                    onClick={() => setSelectedCategory(cat.id)}
                    style={{
                      padding: '0.35rem 0.85rem',
                      fontSize: '0.8rem',
                      fontWeight: 700,
                      borderRadius: 'var(--radius-sm)',
                      border: '1.5px solid #1D1E22',
                      background: isSelected ? '#1E7E34' : '#FFFFFF',
                      color: isSelected ? '#FFFFFF' : '#1D1E22',
                      cursor: 'pointer',
                      boxShadow: isSelected ? 'none' : '1.5px 1.5px 0px #1D1E22',
                      transition: 'all 0.15s ease'
                    }}
                  >
                    {cat.label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* ─── ACCORDION LIST ─── */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginBottom: '3rem' }}>
            {filteredFaqs.length === 0 ? (
              <div style={{ background: '#FFFFFF', border: '1.5px solid #1D1E22', borderRadius: 'var(--radius-md)', padding: '3rem 2rem', textAlign: 'center' }}>
                <HelpCircle size={36} color="var(--color-text-muted)" style={{ margin: '0 auto 1rem auto' }} />
                <h3 style={{ fontSize: '1.2rem', color: '#1D1E22', marginBottom: '0.5rem' }}>
                  {isHi ? 'कोई प्रश्न नहीं मिला' : 'No matching questions found'}
                </h3>
                <p style={{ fontSize: '0.9rem', color: 'var(--color-text-secondary)', marginBottom: '1.25rem' }}>
                  {isHi ? 'कृपया किसी अन्य श्रेणी का चयन करें या सभी प्रश्न देखें।' : 'Please select a different category or view all questions.'}
                </p>
                <button
                  type="button"
                  onClick={() => setSelectedCategory('all')}
                  className="btn-outline-dark"
                  style={{ padding: '0.45rem 1rem', fontSize: '0.82rem', cursor: 'pointer' }}
                >
                  {isHi ? 'फ़िल्टर रीसेट करें' : 'Reset Category Filter'}
                </button>
              </div>
            ) : (
              filteredFaqs.map((faq, index) => {
                const isOpen = openIndex === index;
                const questionText = isHi ? faq.questionHi : faq.question;
                const answerText = isHi ? faq.answerHi : faq.answer;

                return (
                  <div
                    key={faq.id}
                    style={{
                      background: '#FFFFFF',
                      border: '1.5px solid #1D1E22',
                      borderRadius: 'var(--radius-md)',
                      boxShadow: isOpen ? '3px 4px 0px #1D1E22' : '2px 2px 0px #1D1E22',
                      overflow: 'hidden',
                      transition: 'box-shadow 0.2s ease'
                    }}
                  >
                    {/* Accordion Header (Click to Toggle) */}
                    <button
                      type="button"
                      onClick={() => toggleAccordion(index)}
                      aria-expanded={isOpen}
                      style={{
                        width: '100%',
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        padding: '1.25rem 1.5rem',
                        background: isOpen ? '#FAF8F3' : '#FFFFFF',
                        border: 'none',
                        borderBottom: isOpen ? '1px solid #1D1E22' : 'none',
                        cursor: 'pointer',
                        textAlign: 'left',
                        gap: '1rem'
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.85rem' }}>
                        <span
                          style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            width: '28px',
                            height: '28px',
                            borderRadius: '50%',
                            background: isOpen ? '#1E7E34' : '#E8F0FE',
                            color: isOpen ? '#FFFFFF' : '#0A2458',
                            fontSize: '0.8rem',
                            fontWeight: 800,
                            flexShrink: 0
                          }}
                        >
                          {index + 1}
                        </span>
                        <span
                          style={{
                            fontSize: '1.05rem',
                            fontWeight: 700,
                            color: isOpen ? '#0A2458' : '#1D1E22',
                            lineHeight: 1.4
                          }}
                        >
                          {questionText}
                        </span>
                      </div>

                      <div
                        style={{
                          transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)',
                          transition: 'transform 0.25s ease',
                          color: '#1D1E22',
                          flexShrink: 0
                        }}
                      >
                        <ChevronDown size={20} />
                      </div>
                    </button>

                    {/* Accordion Body */}
                    {isOpen && (
                      <div
                        style={{
                          padding: '1.5rem',
                          background: '#FFFFFF',
                          fontSize: '0.95rem',
                          lineHeight: 1.7,
                          color: 'var(--color-text-secondary)',
                          whiteSpace: 'pre-line'
                        }}
                      >
                        {answerText}
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>



        </div>
      </main>

      {/* ─── 3. FOOTER ─── */}
      <Footer onLoginClick={() => navigate('/login')} />
    </div>
  );
};

export default FaqView;
